# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Spacewar/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Spacewar)

$(call add-radio-file-sha1-checked,radio/abl.img,352bf918720708b779feb023823781077eabfc69)
$(call add-radio-file-sha1-checked,radio/aop.img,589f2e1c9367df09af477f519cf794d976f32160)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,b1033e1ccfa8c1420b3b267c9d6de6ae13f59174)
$(call add-radio-file-sha1-checked,radio/cpucp.img,fd28ae866bd3350e06c2b9c6d5c7107845b190cc)
$(call add-radio-file-sha1-checked,radio/devcfg.img,c582c993553f5eb9bfef918c6aae973b03c884e8)
$(call add-radio-file-sha1-checked,radio/dsp.img,afe65f6671c989fc2ee30c52c6ed9cb797f1d5cc)
$(call add-radio-file-sha1-checked,radio/featenabler.img,ee005c695ef000ea1715c009878306006d9aa826)
$(call add-radio-file-sha1-checked,radio/hyp.img,069d6c7329ca06e94f1e75c20c721c280bea60ce)
$(call add-radio-file-sha1-checked,radio/imagefv.img,1423b7c868c691c83d4c1cfeb7d349942f1aff50)
$(call add-radio-file-sha1-checked,radio/keymaster.img,252ad2e7ec8a5682b76f254f007b1c766ddd8d80)
$(call add-radio-file-sha1-checked,radio/modem.img,3b07496f9852f6b3cb52a1259aa4ebe0f6fd749f)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,a9bbe7c4c30a58ecb00cd6cc7a9e3c3cdaa3c4af)
$(call add-radio-file-sha1-checked,radio/qupfw.img,8673170e190122b21db7ab833f1218618aa4397a)
$(call add-radio-file-sha1-checked,radio/shrm.img,e9dda71fb9a97f898a7e7a7fa41c486e9f306b06)
$(call add-radio-file-sha1-checked,radio/tz.img,91958d4ce43e01340a1e7c2d09fc031d05ffe05d)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,2cad3cd25879b6852ae6fd3bf380db086e0867d4)
$(call add-radio-file-sha1-checked,radio/xbl.img,e59185ce7ad058fcd151cfc0c544dbc753712b36)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,262d6ab72938469f4aeb1606a3d87d0e710d0231)

endif
