# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/nothing/Spacewar/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Spacewar)

$(call add-radio-file-sha1-checked,radio/abl.img,b3dfc367c5f5cd1e959e2cff1d06f0bb526663d4)
$(call add-radio-file-sha1-checked,radio/aop.img,e1674506815e996f27e3f061c0801dd136367261)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,d688d3b8872beeef7e8013d0c3af2e28e3f046aa)
$(call add-radio-file-sha1-checked,radio/cpucp.img,26bc4648e9d1c3f64ae742772c25849f884411e8)
$(call add-radio-file-sha1-checked,radio/devcfg.img,6945547fbe0ebf67d3cac34560a3544e1fd6c8fc)
$(call add-radio-file-sha1-checked,radio/dsp.img,afe65f6671c989fc2ee30c52c6ed9cb797f1d5cc)
$(call add-radio-file-sha1-checked,radio/featenabler.img,a7235a4571720a35513e43a14021540a09dde5ae)
$(call add-radio-file-sha1-checked,radio/hyp.img,41d48c1ede0d0971f9d705b79f352fff338c8144)
$(call add-radio-file-sha1-checked,radio/imagefv.img,a31a76d290a056be92e36bfaafe9b316652d4d00)
$(call add-radio-file-sha1-checked,radio/keymaster.img,b586c3867bc0648eeee9b067c99017adcb847fda)
$(call add-radio-file-sha1-checked,radio/modem.img,ec63f5af13d57d104023bdd4eb8d6a13078dbca7)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,1f86afbc681709561311ec0035b8307369aaaab6)
$(call add-radio-file-sha1-checked,radio/qupfw.img,ee85b00b7ef0f0641a18838d7f1dc5ba2e0a992b)
$(call add-radio-file-sha1-checked,radio/shrm.img,e3847237a8af4c0ac98e59561fb13304c792904c)
$(call add-radio-file-sha1-checked,radio/tz.img,e2f8adb767e09fe550ec3e17201a1790a1819054)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,079a1b979b8f33eccd6da42abe7fb8380798d5a7)
$(call add-radio-file-sha1-checked,radio/xbl.img,0ce7ac704a88491836870b4ac8059a405aafdc42)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,1c1df72b1127f5503e2ae794bb95af2c55e56e9d)

endif
